# Generated by Django 3.2.6 on 2021-08-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='areaslista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas', models.CharField(blank=True, max_length=60, null=True, verbose_name='tipo de Areas')),
                ('listrosporpersona', models.FloatField(blank=True, max_length=4, null=True, verbose_name='L/s personas')),
                ('litrosporarea', models.FloatField(blank=True, max_length=4, null=True, verbose_name='L/s area')),
            ],
        ),
    ]
