# Generated by Django 3.2.6 on 2021-08-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Union', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipounion',
            name='union',
            field=models.CharField(max_length=60, verbose_name='unión'),
        ),
    ]
