# Generated by Django 3.2.7 on 2021-12-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Union', '0002_alter_tipounion_union'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipounion',
            options={'verbose_name': 'tipounion', 'verbose_name_plural': 'tipounion'},
        ),
    ]
