# Generated by Django 3.2.6 on 2021-08-18 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Union', '0002_alter_tipounion_union'),
        ('ventilcion', '0002_programa_tipoarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='tipoarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Union.tipounion'),
        ),
    ]
