# Generated by Django 3.2.6 on 2021-08-18 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Union', '0002_alter_tipounion_union'),
        ('areas', '0001_initial'),
        ('ventilcion', '0003_alter_programa_tipoarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='Union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Union.tipounion'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='tipoarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.areaslista'),
        ),
    ]
