# Generated by Django 3.2.6 on 2021-08-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilcion', '0004_auto_20210818_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='accesorios',
        ),
        migrations.AlterField(
            model_name='programa',
            name='Ntramo',
            field=models.IntegerField(blank=True, verbose_name='Número de codos por tramo'),
        ),
    ]
