# Generated by Django 3.2.6 on 2021-08-18 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Union', '0002_alter_tipounion_union'),
        ('ventilcion', '0005_auto_20210818_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='Union',
        ),
        migrations.AddField(
            model_name='programa',
            name='Unión',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Union.tipounion'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='Darea',
            field=models.FloatField(blank=True, max_length=4, null=True, verbose_name='área[m2]'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='Dfinal',
            field=models.BooleanField(default=False, verbose_name='Derivación final'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='d1distancia',
            field=models.FloatField(blank=True, verbose_name='Distncia del tramo[m]'),
        ),
    ]
