# Generated by Django 3.2.6 on 2021-08-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilcion', '0008_programa_npersonas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='Ntramo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de codos por tramo'),
        ),
    ]
