# Generated by Django 3.2.7 on 2021-12-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilcion', '0009_alter_programa_ntramo'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='de3',
            field=models.CharField(blank=True, max_length=4, verbose_name='Derivación 3'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='de1',
            field=models.CharField(blank=True, max_length=4, verbose_name='Derivación 1'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='de2',
            field=models.CharField(blank=True, max_length=4, verbose_name='Derivación 2'),
        ),
    ]
