# Generated by Django 3.2.7 on 2021-12-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('ventilcion', '0010_auto_20211227_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ashrae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='área')),
                ('LPpersona', models.FloatField(blank=True, verbose_name='Litros por persona [l/p]')),
                ('LParea', models.FloatField(blank=True, verbose_name='litros por área[l/p]')),
            ],
        ),
        migrations.AlterField(
            model_name='programa',
            name='tipoarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.areaslista'),
        ),
    ]
