# Generated by Django 3.2.7 on 2021-12-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilcion', '0011_auto_20211229_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='Darea',
            field=models.FloatField(blank=True, max_length=4, null=True, verbose_name='tipo'),
        ),
    ]
