# Generated by Django 3.2.7 on 2021-12-29 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventilcion', '0012_alter_programa_darea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='Darea',
            field=models.FloatField(blank=True, max_length=4, null=True, verbose_name='área[m2]'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='tipoarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventilcion.ashrae'),
        ),
    ]
