# Generated by Django 3.2.7 on 2021-12-30 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('ventilcion', '0014_auto_20211229_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ashrae',
            options={'verbose_name': 'Ashrae', 'verbose_name_plural': 'Ashraes'},
        ),
        migrations.AlterField(
            model_name='programa',
            name='tipoarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.areaslista'),
        ),
    ]
