# Generated by Django 3.2.7 on 2021-12-30 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('ventilcion', '0015_auto_20211230_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='tipoarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.areaslista'),
        ),
    ]
