# Generated by Django 3.2.7 on 2022-01-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventilcion', '0016_alter_programa_tipoarea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ashrae',
        ),
    ]
