# Generated by Django 3.2.7 on 2022-01-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventilcion', '0017_delete_ashrae'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='Codigo',
            field=models.CharField(default=2, max_length=50, verbose_name='Codigo'),
            preserve_default=False,
        ),
    ]
